hotel_auto/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'hotel_auto'
urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    url(r'^inputs/$', views.inputs, name='inputs'),
    url(r'^movement/$', views.movement, name='movement'),
    url(r'^no_movement/$', views.no_movement, name='no_movement'),

]

hotel_automation/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    path('hotel_auto/', include('hotel_auto.urls', namespace='hotel_auto')),
    path('admin/', admin.site.urls),

]

hotel_auto/models.py
from django.db import models

# Create your models here.

hotel_auto/views.py
# Create your views here.
from .utils import create_hotel, movement_in_hotel, check_power_consuption, no_movement_in_hotel, valid_input
from django.shortcuts import render


def index(request):
    return render(request, "inputs.html")


def home(request):
    return render(request, "index.html")


def inputs(request):
    floor_count = int(request.POST['floor_count'])
    print("floor count is - "+str(floor_count))
    main_corridor_count = int(request.POST['main_corridor_count'])
    print("main corridor count is - " + str(main_corridor_count))
    sub_corridor_count = int(request.POST['sub_corridor_count'])
    print("sub corridor count is - " + str(sub_corridor_count))

    hotel = create_hotel(floor_count, main_corridor_count, sub_corridor_count)
    print(hotel)
    floors_list = []
    main_corridor_list = []
    sub_corridor_list = []
    for floors in range(floor_count):
        floors_list.append("floor" + str(floors))
    for main_corridors in range(main_corridor_count):
        main_corridor_list.append("main_corridors"+str(main_corridors))
    for sub_corridors in range(sub_corridor_count):
        sub_corridor_list.append("sub_corridors"+str(sub_corridors))
    hotel = check_power_consuption(hotel, floors_list, main_corridor_list, sub_corridor_list)
    request.session['hotel'] = hotel
    request.session['floors_list'] = floors_list
    request.session['main_corridor_list'] = main_corridor_list
    request.session['sub_corridor_list'] = sub_corridor_list
    valid_floors_list = floors_list
    valid_sub_corridor_list = sub_corridor_list
    return render(request, "show_hotel.html", {'hotel': hotel,
                                               'floors_list': floors_list,
                                               'main_corridor_list': main_corridor_list,
                                               'sub_corridor_list': sub_corridor_list,
                                               'valid_floors_list': valid_floors_list,
                                               'valid_sub_corridor_list': valid_sub_corridor_list,
                                               'alert': False
                                               })


def movement(request):
    movement_dict = {}
    print("Movement Detected In ")
    floor = (request.POST['floor_id'])
    print("floor : " + str(floor))
    movement_dict['floor'] = floor
    main_corridor = (request.POST['main_corridor_id'])
    if main_corridor != '%':
        print("main corridor : " + str(main_corridor))
        movement_dict['main_corridor'] = main_corridor
    sub_corridor = (request.POST['sub_corridor_id'])
    if sub_corridor != '%':
        print("sub corridor : " + str(sub_corridor))
        movement_dict['sub_corridor'] = sub_corridor

    hotel = request.session['hotel']
    floors_list = request.session['floors_list']
    main_corridor_list = request.session['main_corridor_list']
    sub_corridor_list = request.session['sub_corridor_list']

    hotel = movement_in_hotel(hotel, movement_dict)
    hotel = check_power_consuption(hotel, floors_list, main_corridor_list, sub_corridor_list)
    request.session['hotel'] = hotel
    valid_floors_list = []
    valid_sub_corridor_list = []
    for floors in hotel:
        for k, v in hotel[floors].items():
            if 'sub_corridors' in k:
                if hotel[floors][k]['light']:
                    valid_floors_list.append(floors)
                    valid_sub_corridor_list.append(k)
    print(valid_floors_list)
    print(valid_sub_corridor_list)
    return render(request, "show_hotel.html", {'hotel': hotel,
                                               'floors_list': floors_list,
                                               'main_corridor_list': main_corridor_list,
                                               'sub_corridor_list': sub_corridor_list,
                                               'valid_floors_list': valid_floors_list,
                                               'valid_sub_corridor_list': valid_sub_corridor_list,
                                               'alert': False
                                               })


def no_movement(request):
    print("No Movement Detected In ")
    no_movement_dict = {}
    floor = (request.POST['floor_ids'])
    print("floor : " + str(floor))
    no_movement_dict['floor'] = floor
    sub_corridor = (request.POST['sub_corridor_ids'])
    if sub_corridor != '%':
        print("sub corridor : " + str(sub_corridor))
        no_movement_dict['sub_corridor'] = sub_corridor

    hotel = request.session['hotel']
    floors_list = request.session['floors_list']
    main_corridor_list = request.session['main_corridor_list']
    sub_corridor_list = request.session['sub_corridor_list']
    if valid_input(hotel, no_movement_dict):
        hotel = no_movement_in_hotel(hotel, no_movement_dict)
        hotel = check_power_consuption(hotel, floors_list, main_corridor_list, sub_corridor_list)

        alert = False
    else:
        alert = True
    request.session['hotel'] = hotel
    valid_floors_list = []
    valid_sub_corridor_list = []
    for floors in hotel:
        for k, v in hotel[floors].items():
            if 'sub_corridors' in k:
                if hotel[floors][k]['light']:
                    valid_floors_list.append(floors)
                    valid_sub_corridor_list.append(k)
    return render(request, "show_hotel.html", {'hotel': hotel,
                                               'floors_list': floors_list,
                                               'main_corridor_list': main_corridor_list,
                                               'sub_corridor_list': sub_corridor_list,
                                               'valid_floors_list': valid_floors_list,
                                               'valid_sub_corridor_list': valid_sub_corridor_list,
                                               'alert': alert
                                               })

hotel_automation/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're welcome to Hotel Automation System.")

hotel_auto/templates/base.html
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}django-sample-project{% endblock %}</title>
  </head>
  <body>
    <div style="font-size:1.5em">
      {% block header %}Sahaj - Hotel - Automation - Project{% endblock %}
    </div>
    <H2>Welcome to Hotel Automation!</H2>
    {% block content %}
    {% endblock %}
  </body>
</html>

hotel_auto/templates/index.html
{% extends "base.html" %}
{% block content %}
<p>You are visiting the homepage...
  <ul>
    <li><a href="{% url 'hotel_auto:index' %}">Provide Inputs</a></li>
  </ul>
</p>
{% endblock %}

hotel_auto/templates/inputs.html
{% extends "base.html" %}
{% block content %}

<p>You are visiting the inputs page...
<form action="{% url 'hotel_auto:inputs'%}" method="post">
   {% csrf_token %}
  <label for="floor_count">FLOOR COUNT:</label>
  <input type="text" id="floor_count" name="floor_count"><br><br>
  <label for="main_corridor_count">MAIN CORRIDOR PER FLOOR:</label>
  <input type="text" id="main_corridor_count" name="main_corridor_count"><br><br>
  <label for="sub_corridor_count">SUB CORRIDOR COUNT PER FLOOR:</label>
  <input type="text" id="sub_corridor_count" name="sub_corridor_count"><br><br>
  <input type="submit" value="Submit">
</form>
</p>
{% endblock %}

hotel_auto/templates/show_hotel.html
{% extends "base.html" %}
{% block content %}
<p>You have created the default state...
  <table>
  {% for key,value in hotel.items %}
    <tr></tr>
    <tr>
        <td align="center">{{key}}</td>
    </tr>
    <tr>
        <td>
            {% for k,v in value.items %}
                <tr>
                    <td>{{k}}</td>
                    <td>
                        {% for keys,values in v.items %}
                            <td></td>
                            <td>{{keys}} :</td>
                            <td>
                                {% if values %}
                                ON
                                {% else %}
                                OFF
                                {% endif %}
                            </td>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </td>
    </tr>
  {% endfor %}
  </table>
</p>
<br><br>
<p>
<table>
    <td>
        Start Moving....<br><br> Movement Detected In :
      <form action="{% url 'hotel_auto:movement'%}" method="post">
           {% csrf_token %}
          <label for="floor_count">FLOOR :</label>
          <select id="floor_id" name="floor_id">
            <option value="%">---------</option>
            {% for floor in floors_list %}
            <option value="{{ floor}}">{{ floor }}</option>
            {% endfor %}
          </select>
          <br><br>
          <label for="main_corridor_count">MAIN CORRIDOR:</label>
          <select id="main_corridor_id" name="main_corridor_id">
            <option value="%">---------</option>
            {% for main_corridor in main_corridor_list %}
            <option value="{{ main_corridor}}">{{ main_corridor }}</option>
            {% endfor %}
          </select>
          <br><br>
          <label for="sub_corridor_count">SUB CORRIDOR:</label>
          <select id="sub_corridor_id" name="sub_corridor_id">
            <option value="%">---------</option>
            {% for sub_corridor in sub_corridor_list %}
            <option value="{{ sub_corridor}}">{{ sub_corridor }}</option>
            {% endfor %}
          </select>
          <br><br>
          <input type="submit" value="Submit">
      </form>
    </td>
    <td width="100"></td>
    <td>
      No Motion Detected ....<br><br>
      <form action="{% url 'hotel_auto:no_movement'%}" method="post">
           {% csrf_token %}
          <label for="floor_count">FLOOR :</label>
          <select id="floor_ids" name="floor_ids">
            <option value="%">---------</option>
            {% for floor in valid_floors_list %}
            <option value="{{ floor}}">{{ floor }}</option>
            {% endfor %}
          </select>
          <br><br>
          <label for="sub_corridor_count">SUB CORRIDOR:</label>
          <select id="sub_corridor_ids" name="sub_corridor_ids">
            <option value="%">---------</option>
            {% for sub_corridor in valid_sub_corridor_list %}
            <option value="{{ sub_corridor}}">{{ sub_corridor }}</option>
            {% endfor %}
          </select>
          <br><br>
          <input type="submit" value="Submit">
      </form>
        {% if alert %}
            <script>alert("Invalid Combination of Floor and Sub Corridors")</script>
        {% endif %}
    </td>
</table>
</p>
{% endblock %}